/*
Customer Creation API

APIs to manage customers in the database.

API version: 1.0.0
Contact: sharmavivek1709@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CustomerPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerPost200Response{}

// CustomerPost200Response struct for CustomerPost200Response
type CustomerPost200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewCustomerPost200Response instantiates a new CustomerPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerPost200Response() *CustomerPost200Response {
	this := CustomerPost200Response{}
	return &this
}

// NewCustomerPost200ResponseWithDefaults instantiates a new CustomerPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerPost200ResponseWithDefaults() *CustomerPost200Response {
	this := CustomerPost200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CustomerPost200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPost200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CustomerPost200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CustomerPost200Response) SetMessage(v string) {
	o.Message = &v
}

func (o CustomerPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCustomerPost200Response struct {
	value *CustomerPost200Response
	isSet bool
}

func (v NullableCustomerPost200Response) Get() *CustomerPost200Response {
	return v.value
}

func (v *NullableCustomerPost200Response) Set(val *CustomerPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerPost200Response(val *CustomerPost200Response) *NullableCustomerPost200Response {
	return &NullableCustomerPost200Response{value: val, isSet: true}
}

func (v NullableCustomerPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


