openapi: 3.0.0
info:
  title: Customer Creation API
  description: APIs to manage customers in the database.
  version: 1.0.0
  contact:
    name: Vivek Sharma
    email: sharmavivek1709@gmail.com

servers:
  - url: http://localhost:8001
    description: Local development server

tags:
  - name: Customer
    description: Operations related to customers.

paths:
  /customer:
    post:
      summary: Create a new customer in the database
      requestBody:
        description: Customer details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                plan:
                  type: string
                algorithm:
                  type: string
                platform:
                  type: string
              required:
                - name
                - email
                - plan
                - algorithm
                - platform
            example:
              email: vivek@gmail.com
              name: vviveksharma
              plan: Pro Plan
              algorithm: RSA
              platform: Linux
      tags:
        - Customer
      responses:
        "200":
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Customer added successfully with email vivek@gmail.com
        "409":
          description: Conflict - User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User already exists

    get:
      summary: Get customer details using the MasterId
      parameters:
        - name: masterId
          in: query
          required: true
          schema:
            type: string
          description: The Master ID of the customer
      tags:
        - Customer
      responses:
        "200":
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: vivek@gmail.com
                  name:
                    type: string
                    example: vviveksharma
                  plan:
                    type: string
                    example: Pro Plan
                  algorithm:
                    type: string
                    example: RSA
                  platform:
                    type: string
                    example: Linux
                  master_id:
                    type: string
                    example: cd95d3a3-0ffb-4e24-9db9-4d5df3bb228d
