openapi: 3.0.0
info:
  contact:
    email: sharmavivek1709@gmail.com
    name: Vivek Sharma
  description: APIs to manage customers in the database.
  title: Customer Creation API
  version: 1.0.0
servers:
- url: /
tags:
- description: Operations related to customers.
  name: Customer
paths:
  /customer:
    get:
      parameters:
      - description: The Master ID of the customer
        explode: true
        in: query
        name: masterId
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_customer_get_200_response'
          description: Successful retrieval
      summary: Get customer details using the MasterId
      tags:
      - Customer
    post:
      requestBody:
        content:
          application/json:
            example:
              email: vivek@gmail.com
              name: vviveksharma
              plan: Pro Plan
              algorithm: RSA
              platform: Linux
            schema:
              $ref: '#/components/schemas/_customer_post_request'
        description: Customer details
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_customer_post_200_response'
          description: Successful registration
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_customer_post_409_response'
          description: Conflict - User already exists
      summary: Create a new customer in the database
      tags:
      - Customer
components:
  schemas:
    _customer_post_200_response:
      example:
        message: Customer added successfully with email vivek@gmail.com
      properties:
        message:
          example: Customer added successfully with email vivek@gmail.com
          type: string
      type: object
    _customer_post_409_response:
      example:
        message: User already exists
      properties:
        message:
          example: User already exists
          type: string
      type: object
    _customer_get_200_response:
      example:
        master_id: cd95d3a3-0ffb-4e24-9db9-4d5df3bb228d
        name: vviveksharma
        plan: Pro Plan
        email: vivek@gmail.com
        platform: Linux
        algorithm: RSA
      properties:
        email:
          example: vivek@gmail.com
          type: string
        name:
          example: vviveksharma
          type: string
        plan:
          example: Pro Plan
          type: string
        algorithm:
          example: RSA
          type: string
        platform:
          example: Linux
          type: string
        master_id:
          example: cd95d3a3-0ffb-4e24-9db9-4d5df3bb228d
          type: string
      type: object
    _customer_post_request:
      properties:
        email:
          format: email
          type: string
        name:
          type: string
        plan:
          type: string
        algorithm:
          type: string
        platform:
          type: string
      required:
      - algorithm
      - email
      - name
      - plan
      - platform
      type: object
